<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Statistical Test of Significance</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Stats4Every1</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="me.html">About Me</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Statistical Calculation Using R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intoduction.html">Introduction to the Course</a>
    </li>
    <li>
      <a href="what_is_r.html">What is R?</a>
    </li>
    <li>
      <a href="variables.html">R Variables</a>
    </li>
    <li>
      <a href="vectors.html">Vectors</a>
    </li>
    <li>
      <a href="matrix.html">Matrix</a>
    </li>
    <li>
      <a href="sec.html">Basic Statistical Calculations</a>
    </li>
    <li>
      <a href="graphics.html">Graphics</a>
    </li>
    <li>
      <a href="loops.html">Loops and Decisions</a>
    </li>
    <li>
      <a href="factors.html">Factors</a>
    </li>
    <li>
      <a href="df.html">Data frame</a>
    </li>
    <li>
      <a href="functions.html">Functions</a>
    </li>
    <li>
      <a href="distribution.html">Probability Distribution</a>
    </li>
    <li>
      <a href="stest.html">Statistical Test</a>
    </li>
    <li>
      <a href="ftable.html">Frequency Table</a>
    </li>
    <li>
      <a href="pack.html">Using R Packages</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="downloads.html">
    <span class="fa fa-download fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/SarmaSaurav/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.facebook.com/Stats4Everyone">
    <span class="fa fa-facebook fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/saurav-sarma-0044">
    <span class="fa fa-linkedin fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.instagram.com/deka_mastor/">
    <span class="fab fa fab fa-instagram fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Statistical Test of Significance</h1>

</div>


<style>
    #green {
        color: green;
    }
</style>
<style>
    #blue {
        color: blue;
    }
</style>
<style>
    #purple {
        color: purple;
    }
</style>
<div id="green" class="section level1">
<h1></h1>
<p>Statistical inference is the art of generating conclusions about the distribution of the data. A data scientist is often exposed to question that can only be answered scientifically. Therefore, statistical inference is a strategy to test whether a hypothesis is true, i.e. validated by the data.</p>
<blockquote>
<p>HYPOTHESIS: A hypothesis is a statement or assumption that we make about the population which is tested based on information from a sample. The hypothesis is either accepted after the test or is being rejected. There are two types of hypothesis, <strong>null hypothesis</strong> and <strong>alternative hypothesis</strong>.</p>
</blockquote>
<blockquote>
<p>NULL HYPOTHESIS:<br />
A null hypothesis is a general statement or assumption that there is no difference between two factors, or groups or population parameters. It is usually denoted by <span class="math inline">\(H_0\)</span>.</p>
</blockquote>
<blockquote>
<p>ALTERNATIVE HYPOTHESIS:<br />
An alternative hypothesis is a complementary statement to our null hypothesis. This statement is accepted when our null hypothesis is being rejected. It is generally denoted by <span class="math inline">\(H_1\)</span>.</p>
</blockquote>
<p>Here we will discuss about the following statistical tests-</p>
<ul>
<li>t-test</li>
<li>Chi-square test</li>
<li>Analysis of Variation (ANOVA)</li>
</ul>
<div id="blue" class="section level2">
<h2>t-test</h2>
<p>t-test is used when we are comparing a single sample mean with the mean of the population from which the sample is generated or when we are comparing the means of two different samples.</p>
<blockquote>
<p>It is to be noted that t-test is only applicable when the sample size is less than 30</p>
</blockquote>
<div id="t-test-for-single-mean" class="section level3">
<h3>t-test for single mean</h3>
<p>The t-test, or student’s test for single mean, compares the mean of a vector against a theoretical population mean, . The formula used to compute the t-test is:</p>
<p><span class="math display">\[ t= \dfrac{\bar{x}-\mu}{S/\sqrt{n}}\]</span></p>
<p>Here</p>
<ul>
<li><strong><span class="math inline">\(\bar{x}\)</span></strong> refers to the sample mean.</li>
<li><strong><span class="math inline">\(\mu\)</span></strong> to the assumed population mean.</li>
<li><strong>S</strong> is the standard error.</li>
<li><strong>n</strong> the number of observations.</li>
</ul>
<p>Here we are interested in testing the null hypothesis<br />
<span class="math inline">\(H_0: \mu(\text{The population mean})=\mu_0(\text{Some particular value})\)</span></p>
<p>Against the alternative <span class="math inline">\(H_1: \mu(\text{The population mean})\ne\mu_0(\text{Some particular value})\)</span></p>
<p>To evaluate the statistical significance of the t-test, you need to compute the p-value. The p-value ranges from 0 to 1, and is interpreted as follow:</p>
<ul>
<li><p>A p-value lower than 0.05 means you are strongly confident to reject the null hypothesis, thus the alternative hypothesis is accepted.</p></li>
<li><p>A p-value higher than 0.05 indicates that you don’t have enough evidences to reject the null hypothesis and hence it may be accepted.</p></li>
</ul>
<p><strong>Example</strong></p>
<blockquote>
<p>In an All-India level test, 25 students from a certain coaching center secured the following marks<br />
49, 25, 50, 49, 36, 7, 16, 26, 30, 66, 41, 18, 13, 26, 26, 24, 34, 17, 37, 11, 27, 36, 32, 42, 29<br />
The owner of the center claimed that average mark scored by a student (All over India) is 30. Test whether his claim is correct or not.</p>
</blockquote>
<p><strong>Solution:</strong></p>
<p>Here we are testing the null hypothesis: <span class="math inline">\(H_0:\mu=30\)</span><br />
Against the alternative <span class="math inline">\(H_1: \mu \ne 30\)</span></p>
<pre class="r"><code># Enter the data
x=c(49, 25, 50, 49, 36, 7, 16, 26, 30, 66, 41, 18, 13, 26, 26, 24, 34, 17, 37, 11, 27, 36, 32, 42, 29)
# Apply t test sor single mean
t.test(x, mu=30)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  x
## t = 0.24507, df = 24, p-value = 0.8085
## alternative hypothesis: true mean is not equal to 30
## 95 percent confidence interval:
##  24.95326 36.40674
## sample estimates:
## mean of x 
##     30.68</code></pre>
<p>Here, the p-value is 0.8085 which is greater than 0.05, hence we does not have enough evidence to reject his claim. So we should accept his claim. Also, we are 95% sure that the mark of a student will lie within 24.95326~25 and 36.40674~36.</p>
</div>
<div id="t-test-for-paired-mean" class="section level3">
<h3>t-test for paired mean</h3>
<p>This test is used when we want to compare the mean of two sets of data assuming that they have equal amount of variation. The test statistics is calculated using the formula- <span class="math display">\[t=\dfrac{\bar{x}-\bar{y}}{S\sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}\]</span> Here,</p>
<ul>
<li><strong><span class="math inline">\(\bar{x}\)</span></strong> is the mean of first set of data.</li>
<li><strong><span class="math inline">\(\bar{y}\)</span></strong> is the mean of second set of data.</li>
<li><strong>S</strong> is the standard error.</li>
<li><strong><span class="math inline">\(n_1\)</span></strong> is the number of elements in first set.</li>
<li><strong><span class="math inline">\(n_2\)</span></strong> is the number of elements in second set.</li>
</ul>
<p>Here we are interested in testing the null hypothesis <span class="math inline">\(\bar{x}=\bar{y}\)</span></p>
<p>Against the alternative <span class="math inline">\(\bar{x}\ne \bar{y}\)</span></p>
<p><strong>Example</strong></p>
<blockquote>
<p>In an experiment, two different kinds of protein supplement were provided to the members of a Gym. Their strength on a particular scale were measured after one month of using the product. The results are as shown below<br />
Supplement A: 25,32,30,34,24,14,32,24,30,31,35,25.<br />
Supplement B: 44,34,22,10,47,31,40,30,32,35,18,21,35,29,22.<br />
The owner of the gym claimed that the two supplements are not of much difference. Is he correct about his claim? Test using t-test for paired mean.</p>
</blockquote>
<p><strong>Solution</strong></p>
<p>Here, our null hypothesis is, <span class="math inline">\(H_0:\)</span> The two supplements has the same result<br />
Against the alternative that <span class="math inline">\(H_1:\)</span> They are significantly different.</p>
<pre class="r"><code># Enter first set of data
x=c(25,32,30,34,24,14,32,24,30,31,35,25)

# Enter second set of data
y=c(44,34,22,10,47,31,40,30,32,35,18,21,35,29,22)

# Apply t-test

t.test(x,y,var.equal =T)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  x and y
## t = -0.61028, df = 25, p-value = 0.5472
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -8.749507  4.749507
## sample estimates:
## mean of x mean of y 
##        28        30</code></pre>
<p>Since the p-value = 0.5472 is greater than 0.05, so we should accept the null hypothesis and conclude that the owner’s claim is correct.</p>
</div>
</div>
<div id="purple" class="section level2">
<h2>Chi-square test</h2>
<p>Chi-Square test is a statistical method to determine if two categorical variables have a significant correlation between them. Both those variables should be from same population and they should be categorical like − Yes/No, Male/Female, Red/Green etc.</p>
<blockquote>
<p>Chi square test is only applicable when your variable is categorical.</p>
</blockquote>
<p>The formula used for Chi-square test is: <span class="math display">\[\chi^2=\sum_{i=1}^n\dfrac{(O_i-E_i)^2}{E_i^2}\]</span> Where <span class="math inline">\(O_i\)</span> is the observed frequency in each cell and <span class="math inline">\(E_i\)</span> is the expected frequency in that cell.</p>
<p>For example, we can build a data set with observations on people’s ice-cream buying pattern and try to correlate the gender of a person with the flavor of the ice-cream they prefer. If a correlation is found we can plan for appropriate stock of flavors by knowing the number of gender of people visiting.</p>
<p>The function used for performing chi-Square test is <code>chisq.test()</code>.</p>
<p>The basic syntax for creating a chi-square test in R is −</p>
<pre><code>chisq.test(data)</code></pre>
<p>Following is the description of the parameters used −</p>
<ul>
<li><strong>data</strong> is the data in form of a table containing the count value of the variables in the observation.</li>
</ul>
<p>Example:</p>
<blockquote>
<p>15 males and 15 females visiting a shopping mall were asked whether they do online shopping or note. The result is shown below. Check whether their online shopping habit is related to their gender or not.</p>
</blockquote>
<table>
<thead>
<tr class="header">
<th>Gender</th>
<th>Online shopping</th>
<th>Gender</th>
<th>Online Shopping</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Male</td>
<td>Yes</td>
<td>Male</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Male</td>
<td>No</td>
<td>Female</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Female</td>
<td>No</td>
<td>Female</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Female</td>
<td>No</td>
<td>Female</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Male</td>
<td>Yes</td>
<td>Female</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Male</td>
<td>Yes</td>
<td>Male</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Female</td>
<td>Yes</td>
<td>Male</td>
<td>No</td>
</tr>
<tr class="even">
<td>Female</td>
<td>No</td>
<td>Male</td>
<td>No</td>
</tr>
<tr class="odd">
<td>Male</td>
<td>No</td>
<td>Male</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Female</td>
<td>Yes</td>
<td>Female</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Male</td>
<td>No</td>
<td>Male</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Female</td>
<td>No</td>
<td>Male</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Female</td>
<td>No</td>
<td>Female</td>
<td>No</td>
</tr>
<tr class="even">
<td>Female</td>
<td>Yes</td>
<td>Female</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Male</td>
<td>Yes</td>
<td>Male</td>
<td>Yes</td>
</tr>
</tbody>
</table>
<p><strong>Solution:</strong></p>
<p>Here, the null hypothesis that we are testing is, <span class="math inline">\(H_0:\)</span> There is no relationship between gender and online shopping habit. Against the alternative that they are related.</p>
<pre class="r"><code># Create a factor variable for gender 
# We will use 0 for female and 1 for male
gender=c(1,1,0,0,1,1,0,0,1,0,1,0,0,0,1,1,0,0,0,0,1,1,1,1,0,1,1,0,0,1)
gender=factor(gender,labels = c(&quot;Female&quot;,&quot;Male&quot;))

# Create a factor for shopping habit
# 0: No, 1: Yes
habit=c(1,0,0,0,1,1,1,0,0,1,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,0,1,1)
habit=factor(habit, labels = c(&quot;No&quot;, &quot;Yes&quot;))

# Create a cross table
my.data=table(gender,habit)
my.data</code></pre>
<pre><code>##         habit
## gender   No Yes
##   Female  6   9
##   Male    5  10</code></pre>
<pre class="r"><code># apply chi square test

chisq.test(my.data,correct = FALSE)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  my.data
## X-squared = 0.14354, df = 1, p-value = 0.7048</code></pre>
<p>Since the p-value is greater than 0.05, hence we should accept the null hypothesis and conclude that online shopping habit does not depends on gender of a person.</p>
</div>
<div id="anova" class="section level2">
<h2>ANOVA</h2>
<p>Analysis of Variation (ANOVA) is a way of testing whether the variation present in your data set is due to one or more grouping factors or they are just by chance.</p>
<p>Based on the number of groups into which your data is divided, there are two different methods of ANOVA,</p>
<ul>
<li>One way ANOVA</li>
<li>Two way ANOVA</li>
</ul>
<p>If your data is classified according to only one criterion then we will conduct <strong>One way ANOVA</strong> and if your data is divided according to two different criterion then we carry out <strong>Two way ANOVA</strong>.</p>
<p>For example, consider that you have collected the marks of 500 students from 5 different schools of Guwahati. Now obviously the marks of different students will vary. Now we can group them according to their respective schools and see if their marks varies due to their school (Or in Statistical language: Whether school is a significant factor of variation in marks). In this case since we are considering only one grouping factor, so we will have to apply One way ANOVA. On the other hand, if we consider another grouping factor say their gender and want to see whether gender is a significant factor of variation or not along with their school, then we will have to apply Two way ANOVA.</p>
<p>The basic syntax for an ANOVA test is</p>
<pre><code>aov(formula, data)</code></pre>
<p>Where,</p>
<ul>
<li><strong>formula</strong>: The relationship we want to test.</li>
<li><strong>data</strong>: The data set we are using.</li>
</ul>
<blockquote>
<p>It should be noted that to perform ANOVA, your data should be a numerical variable and grouping variable should be a factor of at least 2 levels.</p>
</blockquote>
<div id="one-way-anova" class="section level4">
<h4>One way ANOVA:</h4>
<p>Example:</p>
<blockquote>
<p>Marks of 30 students were collected from 3 different schools for both male and female. Analyse whether school and gender are significant factor for variation in marks.</p>
</blockquote>
<p>Solution:</p>
<p>The data set we will be using here can be downloaded from here: <a href="files/anova.csv" download> ANOVA Data </a></p>
<ul>
<li>Save the downloaded anova.csv file to your R working directory.</li>
</ul>
<p>Here, we are interested in testing the null hypothesis that “Gender is not a significant factor for variation in marks”</p>
<p>The analysis can be carried out using the following R program-</p>
<pre class="r"><code># Import the data set
data=read.csv(&quot;anova.csv&quot;, header = TRUE)
# lets dee the structure of the data
str(data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  3 variables:
##  $ School: Factor w/ 3 levels &quot;School A&quot;,&quot;School B&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Gender: Factor w/ 2 levels &quot;Female&quot;,&quot;Male&quot;: 2 2 2 2 2 1 1 1 1 1 ...
##  $ Marks : int  54 47 89 23 84 74 55 64 39 48 ...</code></pre>
<pre class="r"><code># Here we have two factor variables &quot;Gender&quot; and &quot;School&quot;
# and a int variable &quot;Marks&quot;</code></pre>
<pre class="r"><code># apply one way anova

one_way_school=aov(Marks~School, data=data)
summary(one_way_school)</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## School       2    150    75.2   0.189  0.829
## Residuals   27  10762   398.6</code></pre>
<p>Since the p-value 0.829 is greater than 0.05, hence we should accept our null hypothesis and conclude that school is not a significant factor of variation in marks of students.</p>
<p>Again if we want to check whether gender is a significant factor of variation, then we can use the following program-</p>
<pre class="r"><code>one_way_gender=aov(Marks~Gender, data=data)
summary(one_way_gender)</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Gender       1    173   172.8   0.451  0.508
## Residuals   28  10740   383.6</code></pre>
<p>Here also, the p-value(0.508) is greater than 0.05 and hence we conclude that gender is also not a significant factor of variation.</p>
</div>
<div id="two-way-anova" class="section level4">
<h4>Two Way ANOVA:</h4>
<p>Here we are interested in testing the null hypothesis that gender and school both are not a significant factor of variation in marks of student.</p>
<pre class="r"><code>two_way_aov=aov(Marks~School+Gender, data=data)
summary(two_way_aov)</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## School       2    150    75.2   0.186  0.832
## Gender       1    222   222.5   0.549  0.465
## Residuals   26  10540   405.4</code></pre>
<p>Since p-value for both School and Gender are greater than 0.05, hence both are insignificant for the variation of marks.</p>
</div>
</div>
</div>

<p>Copyright &copy; 2018 Saurav Sarma. All rights reserved.<p>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
